version: 0.1

# =============== GENERAL SETTINGS ===============
TIMEOUT: 90  # refresh page every 80s

# =============== VISA CENTER SELECTION ===============
CENTER1:
  - 'England'
  - 'Manchester'
  - 'Normal'
  - 'Tourism'
CENTER2:
  - 'Scotland'
  - 'Edinburgh'
  - 'Normal'
  - 'Tourism'
CENTER3:
  - 'Bristol'
  - 'London'
  - 'Normal'
  - 'Tourist'

# =============== PERSONAL CONFIG FOR VISA ===============
OPENED_PAGE: 'https://uk.blsspainvisa.com/visa4spain'
EMAIL:
  - 'tianfuvisa23003@gmail.com'
  - 'tianfuvisa23004@gmail.com'
  - 'binliu918@gmail.com'
PASSWORD:
  - 'Tianfu2023/'
  - 'Tianfu2023/'
  - 'Tianfu2023/'
